# Notes on advancements of NLNM

1/26/2025 - Rewarded Load:

1. Hand-to-hand NLNM combat is expected to be backed by openly proclaimed moral grounds for initiating an aggression.  This aligns with the recorded post imperial realities of the feudal systems (backing research needed). The Early Imperial systems are associated with the currently hypothesized Systemized Violence. The following Feudal Systems are associated with the Open Threat of Violence.  Examples of such progressions are well known in Europe, Japan and are hypothesized to have taken place in all parts of the world, starting with the Assyrian Empire and historically evolving to less massive and severe levels of Systemized Violence.  The Open Threat of Violence allows for the morally lifting "Иду на вы" principle of declaring aggressive intentions.  This aligns with the hypothesized low economic incentive for territorial aggression in the resource abundant economic system of nuclear fusion energy and robotization, and thus necessitates backing of aggression on openly declared moral grounds.  The right to defend own territory and cultural ways is by default implied to have superior moral grounds.
2. Hand-to-hand NLNM combat is expected to be the "boots on the ground" earning the right of taking and holding territory, in the associated "slow and steady" way, if necessary for short or medium term occupation.  It is expected to take place in rural or unsettled areas.
3. The projectile based NLNM combat is expected to provide the most expedient armament augmentation path to urban NLNM combat.  The possible presence of non-combatants in urban areas can be mitigated by their mandatory equipment of suffocation-preventing helpments, thus only placing them at risk of full or partial incapacitation - literally being glued in place.  The Non-Lethal, Non-Mutilating, No Serious Injury nature of combat is expected to prevent atrocities against the present civilian population.
4. Exposure of the short term continents to simulated heavy and medium near-mech combat both prepares them for cross-service combat (prepared for the case of planetary emergency) and gives them the assurance of the might of the armed forces standing bind them in societal interactions.
5. Mass participation of short term personnel (serving for 1 to 4 years) in hand-to-hand combat is expected to build the defender mentality, associated with their armament of defensive, collectively highly effective shields and strike softening "boxing" gloves (in "boxing" version of hand-to-hand NLNM combat).  The exposure to service in Open Threat of Violence systems in combination with mass participation in NLNM combat is expected to reduce the levels of societal violence in All discharged veterans, without the physical and mental handicap associated with historically preceding combat systems.  Ultimately the expectation is personal growth past the natural stage of "proud warrior" (hypothetically linked to early-developmental and early-pre-historical ages of glorified, poorly controlled and thus potentially Total Violence) - in a controlled, disciplined and time-efficient manner.

